using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using TestsGenerator.Example;

namespace Tests
{
    [TestFixture]
    public class ExampleClass2Tests
    {
        private ExampleClass2 _exampleClass2;
        [SetUp]
        public void SetUp()
        {
            int number = default;
            _exampleClass2 = new ExampleClass2(number);
        }

        [Test]
        public void VoidMethodWithParametersTest()
        {
            int number = default;
            int actual = _exampleClass2.VoidMethodWithParameters(number);
            int expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
    }
}